### ISSUE TITLE
CAPTCHAs.IO Integration

### ISSUE THREAD

**Issue by articlefr** [W3D3/SteamAccountSwitcher2#6]
Hi,

I'd like to ask support for integration of https://captchas.io/ captcha solving service.

Thanks!
Glenn Prialde

**Comment by Aidoboy** [comment]
1. This application has no captchas?
2. If it did, wouldn't that break Steam's ToS?
3. It costs money? This is a hobby project.
4. You own it?

**Comment by W3D3** [comment]
I have no clue why this application would need something like that, I never had to enter a captcha to log into Steam.
